FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu18.04

RUN mkdir /usr/app
WORKDIR /usr/app

RUN apt-get update \
    && apt-get install -y vim wget gcc make git cmake g++ curl

# For Python venv
RUN apt-get install -y python3.8-venv

COPY requirements.txt requirements.txt
RUN python3 -m venv env \
    && source env/bin/activate \
    & pip install -r requirements.txt

EXPOSE 8000